In [1]:
import numpy as np


source_map = np.array(list('1110001110001110011001100')).astype(np.int)
source_map = source_map.reshape(5, 5)
print('Source Data:')
print(source_map)

filter1 = np.array(list('101010101')).astype(np.int).reshape(3, 3)
print('Filiter:')
print(filter1)

Source Data:
[[1 1 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 1 1 0 0]]
Filiter:
[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [2]:
width = height = source_map.shape[0] - filter1.shape[0] + 1
result = np.zeros((width, height))

for i in range(width):
    for j in range(height):
        value1 = source_map[i:i + filter1.shape[0], j:j + filter1.shape[1]] * filter1
        result[i, j] = np.sum(value1)

print(result)

[[4. 3. 4.]
 [2. 4. 3.]
 [2. 3. 4.]]


In [4]:
from scipy.signal import convolve2d


convolve2d(source_map, filter1, mode='valid')

array([[4, 3, 4],
       [2, 4, 3],
       [2, 3, 4]])

## Convolutions

In [4]:
from skimage.exposure import rescale_intensity
import numpy as np
import cv2

def convolve(image, kernel):
    (iH, iW) = image.shape[:2]
    (kH, kW) = kernel.shape[:2]
    
    pad = int((kW - 1) / 2)
    image = cv2.copyMakeBorder(image, pad, pad, pad, pad, cv2.BORDER_REPLICATE)
    output = np.zeros((iH, iW), dtype='float32')
    
    for y in np.arange(pad, iH + pad):
        for x in np.arange(pad, iW + pad):
            roi  = image[y - pad:y + pad + 1, x - pad:x + pad + 1]
            k = (roi * kernel).sum()
            output[y - pad, x - pad] = k
            
    output = rescale_intensity(output, in_range=(0, 255))
    output = (output * 255).astype('uint8')
    
    return output

In [2]:
import skimage
import cv2


image = skimage.data.chelsea()
cv2.imshow('original', image)

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow('gray', gray)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
smallBlur = np.ones((7, 7), dtype='float') * (1.0 / (7 * 7))

convoleOutput = convolve(gray, smallBlur)
opencvOutput = cv2.filter2D(gray, -1, smallBlur)
cv2.imshow('little Blur', convoleOutput)

largeBlur = np.ones((21, 21), dtype='float') * (1.0 / (21 * 21))

convoleOutput = convolve(gray, largeBlur)
opencvOutput = cv2.filter2D(gray, -1, largeBlur)
cv2.imshow('little Blur', convoleOutput)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
sharpen = np.array((
    [0, -1, 0],
    [-1, 5, -1],
    [0, -1, 0]
), dtype='int')

convoleOutput = convolve(gray, sharpen)
opencvOutput = cv2.filter2D(gray, -1, sharpen)
cv2.imshow('sharpen', convoleOutput)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
sharpen = np.array((
    [0, 1, 0],
    [1, 4, 1],
    [0, 1, 0]
), dtype='int')

convoleOutput = convolve(gray, sharpen)
opencvOutput = cv2.filter2D(gray, -1, sharpen)
cv2.imshow('sharpen', convoleOutput)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
sharpen = np.array((
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
), dtype='int')

convoleOutput = convolve(gray, sharpen)
opencvOutput = cv2.filter2D(gray, -1, sharpen)
cv2.imshow('sharpen', convoleOutput)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
sharpen = np.array((
    [-1, -2, 1],
    [0, 0, 0],
    [-1, 2, 1]
), dtype='int')

convoleOutput = convolve(gray, sharpen)
opencvOutput = cv2.filter2D(gray, -1, sharpen)
cv2.imshow('sharpen', convoleOutput)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Pooling Layer