In [1]:
import numpy as np


source_map = np.array(list('1110001110001110011001100')).astype(np.int)
source_map = source_map.reshape(5, 5)
print('Source Data:')
print(source_map)

filter1 = np.array(list('101010101')).astype(np.int).reshape(3, 3)
print('Filiter:')
print(filter1)

Source Data:
[[1 1 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 1 1 0 0]]
Filiter:
[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [2]:
width = height = source_map.shape[0] - filter1.shape[0] + 1
result = np.zeros((width, height))

for i in range(width):
    for j in range(height):
        value1 = source_map[i:i + filter1.shape[0], j:j + filter1.shape[1]] * filter1
        result[i, j] = np.sum(value1)

print(result)

[[4. 3. 4.]
 [2. 4. 3.]
 [2. 3. 4.]]


In [4]:
from scipy.signal import convolve2d


convolve2d(source_map, filter1, mode='valid')

array([[4, 3, 4],
       [2, 4, 3],
       [2, 3, 4]])